// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LeGarage.Infrastructure.Models;

public partial class WorkshopContext : DbContext
{
    public WorkshopContext(DbContextOptions<WorkshopContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<Baseentity> Baseentities { get; set; }

    public virtual DbSet<Bridge> Bridges { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Externalservice> Externalservices { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Pauserecord> Pauserecords { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Paymentallocation> Paymentallocations { get; set; }

    public virtual DbSet<Paymentmethod> Paymentmethods { get; set; }

    public virtual DbSet<Providedservice> Providedservices { get; set; }

    public virtual DbSet<Providedservicecategory> Providedservicecategories { get; set; }

    public virtual DbSet<Provider> Providers { get; set; }

    public virtual DbSet<Sparepart> Spareparts { get; set; }

    public virtual DbSet<Sparepartcategory> Sparepartcategories { get; set; }

    public virtual DbSet<Stockreplenishment> Stockreplenishments { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<Taskexternalserviceusage> Taskexternalserviceusages { get; set; }

    public virtual DbSet<Taskpartusage> Taskpartusages { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    public virtual DbSet<Warehousestock> Warehousestocks { get; set; }

    public virtual DbSet<Workorder> Workorders { get; set; }

    public virtual DbSet<Workshop> Workshops { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);
        foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e=>e.GetForeignKeys()))
        {
            relationship.DeleteBehavior = DeleteBehavior.Restrict;
        }



        modelBuilder.Entity<Externalservice>(entity =>
        {
            entity.HasKey(e => e.Externalserviceid).HasName("pk_externalservice");

            entity.ToTable("externalservice");

            entity.HasIndex(e => e.Externalserviceid, "externalservice_pk").IsUnique();

            entity.Property(e => e.Externalserviceid)
                .ValueGeneratedNever()
                .HasColumnName("externalserviceid");
            entity.Property(e => e.Category)
                .HasMaxLength(254)
                .HasColumnName("category");
            entity.Property(e => e.Cost).HasColumnName("cost");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
            entity.Property(e => e.Unit)
                .HasMaxLength(254)
                .HasColumnName("unit");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Invoiceid).HasName("pk_invoice");

            entity.ToTable("invoice");

            entity.HasIndex(e => e.Clientid, "association20_fk");

            entity.HasIndex(e => e.Invoiceid, "invoice_pk").IsUnique();

            entity.Property(e => e.Invoiceid)
                .ValueGeneratedNever()
                .HasColumnName("invoiceid");
            entity.Property(e => e.Clientid).HasColumnName("clientid");
            entity.Property(e => e.Discountamount).HasColumnName("discountamount");
            entity.Property(e => e.Duedate).HasColumnName("duedate");
            entity.Property(e => e.Issuedate).HasColumnName("issuedate");
            entity.Property(e => e.Status)
                .HasMaxLength(254)
                .HasColumnName("status");
            entity.Property(e => e.Subtotalexternalservices).HasColumnName("subtotalexternalservices");
            entity.Property(e => e.Subtotallabor).HasColumnName("subtotallabor");
            entity.Property(e => e.Subtotalparts).HasColumnName("subtotalparts");
            entity.Property(e => e.Taxamount).HasColumnName("taxamount");
            entity.Property(e => e.Totalamount).HasColumnName("totalamount");

            entity.HasOne(d => d.Client).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.Clientid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_invoice_associati_client");
        });

        modelBuilder.Entity<Pauserecord>(entity =>
        {
            entity.HasKey(e => e.Pauserecordid).HasName("pk_pauserecord");

            entity.ToTable("pauserecord");

            entity.HasIndex(e => e.Taskid, "association24_fk");

            entity.HasIndex(e => e.Pauserecordid, "pauserecord_pk").IsUnique();

            entity.Property(e => e.Pauserecordid)
                .ValueGeneratedNever()
                .HasColumnName("pauserecordid");
            entity.Property(e => e.Endtime).HasColumnName("endtime");
            entity.Property(e => e.Pauseduration).HasColumnName("pauseduration");
            entity.Property(e => e.Reason)
                .HasMaxLength(254)
                .HasColumnName("reason");
            entity.Property(e => e.Starttime).HasColumnName("starttime");
            entity.Property(e => e.Taskid).HasColumnName("taskid");

            entity.HasOne(d => d.Task).WithMany(p => p.Pauserecords)
                .HasForeignKey(d => d.Taskid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_pauserec_associati_task");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Paymentid).HasName("pk_payment");

            entity.ToTable("payment");

            entity.HasIndex(e => e.Clientid, "association22_fk");

            entity.HasIndex(e => e.Paymentmethodid, "association23_fk");

            entity.HasIndex(e => e.Paymentid, "payment_pk").IsUnique();

            entity.HasIndex(e => e.PayPaymentid, "refundclient_fk");

            entity.Property(e => e.Paymentid)
                .ValueGeneratedNever()
                .HasColumnName("paymentid");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Clientid).HasColumnName("clientid");
            entity.Property(e => e.PayPaymentid).HasColumnName("pay_paymentid");
            entity.Property(e => e.Paymentdate).HasColumnName("paymentdate");
            entity.Property(e => e.Paymentmethodid).HasColumnName("paymentmethodid");
            entity.Property(e => e.Paymenttype)
                .HasMaxLength(254)
                .HasColumnName("paymenttype");

            entity.HasOne(d => d.Client).WithMany(p => p.Payments)
                .HasForeignKey(d => d.Clientid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_payment_associati_client");

            entity.HasOne(d => d.PayPayment).WithMany(p => p.InversePayPayment)
                .HasForeignKey(d => d.PayPaymentid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_payment_refundcli_payment");

            entity.HasOne(d => d.Paymentmethod).WithMany(p => p.Payments)
                .HasForeignKey(d => d.Paymentmethodid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_payment_associati_paymentm");
        });

        modelBuilder.Entity<Paymentallocation>(entity =>
        {
            entity.HasKey(e => new { e.Invoiceid, e.Paymentid, e.Paymentallocationid }).HasName("pk_paymentallocation");

            entity.ToTable("paymentallocation");

            entity.HasIndex(e => e.Invoiceid, "association21_fk");

            entity.HasIndex(e => e.Paymentid, "association21_fk2");

            entity.HasIndex(e => new { e.Invoiceid, e.Paymentid, e.Paymentallocationid }, "paymentallocation_pk").IsUnique();

            entity.Property(e => e.Invoiceid).HasColumnName("invoiceid");
            entity.Property(e => e.Paymentid).HasColumnName("paymentid");
            entity.Property(e => e.Paymentallocationid).HasColumnName("paymentallocationid");
            entity.Property(e => e.Amountallocated).HasColumnName("amountallocated");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Paymentallocations)
                .HasForeignKey(d => d.Invoiceid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_paymenta_associati_invoice");

            entity.HasOne(d => d.Payment).WithMany(p => p.Paymentallocations)
                .HasForeignKey(d => d.Paymentid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_paymenta_associati_payment");
        });

        modelBuilder.Entity<Paymentmethod>(entity =>
        {
            entity.HasKey(e => e.Paymentmethodid).HasName("pk_paymentmethod");

            entity.ToTable("paymentmethod");

            entity.HasIndex(e => e.Paymentmethodid, "paymentmethod_pk").IsUnique();

            entity.Property(e => e.Paymentmethodid)
                .ValueGeneratedNever()
                .HasColumnName("paymentmethodid");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Providedservice>(entity =>
        {
            entity.HasKey(e => e.Providedserviceid).HasName("pk_providedservice");

            entity.ToTable("providedservice");

            entity.HasIndex(e => e.Providedservicecategoryid, "association1_fk");

            entity.HasIndex(e => e.Providedserviceid, "providedservice_pk").IsUnique();

            entity.Property(e => e.Providedserviceid)
                .ValueGeneratedNever()
                .HasColumnName("providedserviceid");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Estimatedhours).HasColumnName("estimatedhours");
            entity.Property(e => e.Mincharge).HasColumnName("mincharge");
            entity.Property(e => e.Name).HasColumnName("name");
            entity.Property(e => e.Pricingmodel)
                .HasMaxLength(254)
                .HasColumnName("pricingmodel");
            entity.Property(e => e.Providedservicecategoryid).HasColumnName("providedservicecategoryid");
            entity.Property(e => e.Rate).HasColumnName("rate");

            entity.HasOne(d => d.Providedservicecategory).WithMany(p => p.Providedservices)
                .HasForeignKey(d => d.Providedservicecategoryid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_provided_associati_provided");
        });

        modelBuilder.Entity<Providedservicecategory>(entity =>
        {
            entity.HasKey(e => e.Providedservicecategoryid).HasName("pk_providedservicecategory");

            entity.ToTable("providedservicecategory");

            entity.HasIndex(e => e.Providedservicecategoryid, "providedservicecategory_pk").IsUnique();

            entity.Property(e => e.Providedservicecategoryid)
                .ValueGeneratedNever()
                .HasColumnName("providedservicecategoryid");
            entity.Property(e => e.Code)
                .HasMaxLength(254)
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Provider>(entity =>
        {
            entity.HasKey(e => e.Providerid).HasName("pk_provider");

            entity.ToTable("provider");

            entity.HasIndex(e => e.Providerid, "provider_pk").IsUnique();

            entity.Property(e => e.Providerid)
                .ValueGeneratedNever()
                .HasColumnName("providerid");
            entity.Property(e => e.Address)
                .HasMaxLength(254)
                .HasColumnName("address");
            entity.Property(e => e.Companyid)
                .HasMaxLength(254)
                .HasColumnName("companyid");
            entity.Property(e => e.Contactperson)
                .HasMaxLength(254)
                .HasColumnName("contactperson");
            entity.Property(e => e.Email)
                .HasMaxLength(254)
                .HasColumnName("email");
            entity.Property(e => e.Legalname)
                .HasMaxLength(254)
                .HasColumnName("legalname");
            entity.Property(e => e.Paymentterms)
                .HasMaxLength(254)
                .HasColumnName("paymentterms");
            entity.Property(e => e.Phone)
                .HasMaxLength(254)
                .HasColumnName("phone");
        });

        modelBuilder.Entity<Sparepart>(entity =>
        {
            entity.HasKey(e => e.Sparepartid).HasName("pk_sparepart");

            entity.ToTable("sparepart");

            entity.HasIndex(e => e.Sparepartcategoryid, "association5_fk");

            entity.HasIndex(e => e.Sparepartid, "sparepart_pk").IsUnique();

            entity.Property(e => e.Sparepartid)
                .ValueGeneratedNever()
                .HasColumnName("sparepartid");
            entity.Property(e => e.Availablequantity).HasColumnName("availablequantity");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Minimumstock).HasColumnName("minimumstock");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
            entity.Property(e => e.Sparepartcategoryid).HasColumnName("sparepartcategoryid");
            entity.Property(e => e.Sparepartcode)
                .HasMaxLength(254)
                .HasColumnName("sparepartcode");
            entity.Property(e => e.Unitprice).HasColumnName("unitprice");

            entity.HasOne(d => d.Sparepartcategory).WithMany(p => p.Spareparts)
                .HasForeignKey(d => d.Sparepartcategoryid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_sparepar_associati_sparepar");
        });

        modelBuilder.Entity<Sparepartcategory>(entity =>
        {
            entity.HasKey(e => e.Sparepartcategoryid).HasName("pk_sparepartcategory");

            entity.ToTable("sparepartcategory");

            entity.HasIndex(e => e.Sparepartcategoryid, "sparepartcategory_pk").IsUnique();

            entity.Property(e => e.Sparepartcategoryid)
                .ValueGeneratedNever()
                .HasColumnName("sparepartcategoryid");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Stockreplenishment>(entity =>
        {
            entity.HasKey(e => e.Stockreplenishmentid).HasName("pk_stockreplenishment");

            entity.ToTable("stockreplenishment");

            entity.HasIndex(e => e.Warehouseid, "association25_fk");

            entity.HasIndex(e => e.Sparepartid, "association26_fk");

            entity.HasIndex(e => e.Providerid, "association27_fk");

            entity.HasIndex(e => e.Stockreplenishmentid, "stockreplenishment_pk").IsUnique();

            entity.Property(e => e.Stockreplenishmentid)
                .ValueGeneratedNever()
                .HasColumnName("stockreplenishmentid");
            entity.Property(e => e.Discount).HasColumnName("discount");
            entity.Property(e => e.Margin).HasColumnName("margin");
            entity.Property(e => e.Providerid).HasColumnName("providerid");
            entity.Property(e => e.Receivedquantity).HasColumnName("receivedquantity");
            entity.Property(e => e.Receptiondate).HasColumnName("receptiondate");
            entity.Property(e => e.Receptionreceipt)
                .HasMaxLength(254)
                .HasColumnName("receptionreceipt");
            entity.Property(e => e.Sparepartid).HasColumnName("sparepartid");
            entity.Property(e => e.Unitpriceatpurchase).HasColumnName("unitpriceatpurchase");
            entity.Property(e => e.Vat).HasColumnName("vat");
            entity.Property(e => e.Warehouseid).HasColumnName("warehouseid");

            entity.HasOne(d => d.Provider).WithMany(p => p.Stockreplenishments)
                .HasForeignKey(d => d.Providerid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_stockrep_associati_provider");

            entity.HasOne(d => d.Sparepart).WithMany(p => p.Stockreplenishments)
                .HasForeignKey(d => d.Sparepartid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_stockrep_associati_sparepar");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Stockreplenishments)
                .HasForeignKey(d => d.Warehouseid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_stockrep_associati_warehous");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Taskid).HasName("pk_task");

            entity.ToTable("task");

            entity.HasIndex(e => e.Bridgeid, "association10_fk");

            entity.HasIndex(e => e.Providedserviceid, "association11_fk");

            entity.HasIndex(e => e.Userid, "association12_fk");

            entity.HasIndex(e => e.Workorderid, "association13_fk");

            entity.HasIndex(e => e.Taskid, "task_pk").IsUnique();

            entity.Property(e => e.Taskid)
                .ValueGeneratedNever()
                .HasColumnName("taskid");
            entity.Property(e => e.Bridgeid).HasColumnName("bridgeid");
            entity.Property(e => e.Description)
                .HasMaxLength(254)
                .HasColumnName("description");
            entity.Property(e => e.Endtime).HasColumnName("endtime");
            entity.Property(e => e.Externalservicecost).HasColumnName("externalservicecost");
            entity.Property(e => e.Laborcost).HasColumnName("laborcost");
            entity.Property(e => e.Partscost).HasColumnName("partscost");
            entity.Property(e => e.Providedserviceid).HasColumnName("providedserviceid");
            entity.Property(e => e.Starttime).HasColumnName("starttime");
            entity.Property(e => e.Tasktotalcost).HasColumnName("tasktotalcost");
            entity.Property(e => e.Userid).HasColumnName("userid");
            entity.Property(e => e.Workorderid).HasColumnName("workorderid");

            entity.HasOne(d => d.Bridge).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Bridgeid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_task_associati_bridge");

            entity.HasOne(d => d.Providedservice).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Providedserviceid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_task_associati_provided");

            entity.HasOne(d => d.User).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Userid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_task_associati_user");

            entity.HasOne(d => d.Workorder).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Workorderid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_task_associati_workorde");
        });

        modelBuilder.Entity<Taskexternalserviceusage>(entity =>
        {
            entity.HasKey(e => e.Taskexternalserviceusageid).HasName("pk_taskexternalserviceusage");

            entity.ToTable("taskexternalserviceusage");

            entity.HasIndex(e => e.Taskid, "association33_fk");

            entity.HasIndex(e => e.Externalserviceid, "association34_fk");

            entity.HasIndex(e => e.Providerid, "association35_fk");

            entity.HasIndex(e => e.Taskexternalserviceusageid, "taskexternalserviceusage_pk").IsUnique();

            entity.Property(e => e.Taskexternalserviceusageid)
                .ValueGeneratedNever()
                .HasColumnName("taskexternalserviceusageid");
            entity.Property(e => e.Cost).HasColumnName("cost");
            entity.Property(e => e.Externalserviceid).HasColumnName("externalserviceid");
            entity.Property(e => e.Invoicenumber)
                .HasMaxLength(254)
                .HasColumnName("invoicenumber");
            entity.Property(e => e.Providerid).HasColumnName("providerid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Taskid).HasColumnName("taskid");
            entity.Property(e => e.Unitprice).HasColumnName("unitprice");

            entity.HasOne(d => d.Externalservice).WithMany(p => p.Taskexternalserviceusages)
                .HasForeignKey(d => d.Externalserviceid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskexte_associati_external");

            entity.HasOne(d => d.Provider).WithMany(p => p.Taskexternalserviceusages)
                .HasForeignKey(d => d.Providerid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskexte_associati_provider");

            entity.HasOne(d => d.Task).WithMany(p => p.Taskexternalserviceusages)
                .HasForeignKey(d => d.Taskid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskexte_associati_task");
        });

        modelBuilder.Entity<Taskpartusage>(entity =>
        {
            entity.HasKey(e => e.Taskpartusageid).HasName("pk_taskpartusage");

            entity.ToTable("taskpartusage");

            entity.HasIndex(e => e.Taskid, "association28_fk");

            entity.HasIndex(e => e.Warehouseid, "association29_fk");

            entity.HasIndex(e => e.Sparepartid, "association30_fk");

            entity.HasIndex(e => e.Taskpartusageid, "taskpartusage_pk").IsUnique();

            entity.Property(e => e.Taskpartusageid)
                .ValueGeneratedNever()
                .HasColumnName("taskpartusageid");
            entity.Property(e => e.Deliverynote)
                .HasMaxLength(254)
                .HasColumnName("deliverynote");
            entity.Property(e => e.Quantityused).HasColumnName("quantityused");
            entity.Property(e => e.Sparepartid).HasColumnName("sparepartid");
            entity.Property(e => e.Taskid).HasColumnName("taskid");
            entity.Property(e => e.Totalpartcost).HasColumnName("totalpartcost");
            entity.Property(e => e.Unitprice).HasColumnName("unitprice");
            entity.Property(e => e.Warehouseid).HasColumnName("warehouseid");

            entity.HasOne(d => d.Sparepart).WithMany(p => p.Taskpartusages)
                .HasForeignKey(d => d.Sparepartid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskpart_associati_sparepar");

            entity.HasOne(d => d.Task).WithMany(p => p.Taskpartusages)
                .HasForeignKey(d => d.Taskid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskpart_associati_task");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Taskpartusages)
                .HasForeignKey(d => d.Warehouseid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_taskpart_associati_warehous");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Userid).HasName("pk_user");

            entity.ToTable("User");

            entity.HasIndex(e => e.Userid, "user_pk").IsUnique();

            entity.Property(e => e.Userid)
                .ValueGeneratedNever()
                .HasColumnName("userid");
            entity.Property(e => e.Address)
                .HasMaxLength(254)
                .HasColumnName("address");
            entity.Property(e => e.Availabilitystatus)
                .HasMaxLength(254)
                .HasColumnName("availabilitystatus");
            entity.Property(e => e.Email)
                .HasMaxLength(254)
                .HasColumnName("email");
            entity.Property(e => e.Hiredate).HasColumnName("hiredate");
            entity.Property(e => e.Lastname)
                .HasMaxLength(254)
                .HasColumnName("lastname");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(254)
                .HasColumnName("password");
            entity.Property(e => e.Phonenumber)
                .HasMaxLength(254)
                .HasColumnName("phonenumber");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Vehicleid).HasName("pk_vehicle");

            entity.ToTable("vehicle");

            entity.HasIndex(e => e.Clientid, "association3_fk");

            entity.HasIndex(e => e.Vehicleid, "vehicle_pk").IsUnique();

            entity.Property(e => e.Vehicleid)
                .ValueGeneratedNever()
                .HasColumnName("vehicleid");
            entity.Property(e => e.Clientid).HasColumnName("clientid");
            entity.Property(e => e.Fueltype)
                .HasMaxLength(254)
                .HasColumnName("fueltype");
            entity.Property(e => e.Make)
                .HasMaxLength(254)
                .HasColumnName("make");
            entity.Property(e => e.Mileage).HasColumnName("mileage");
            entity.Property(e => e.Model)
                .HasMaxLength(254)
                .HasColumnName("model");
            entity.Property(e => e.Platenumber)
                .HasMaxLength(254)
                .HasColumnName("platenumber");
            entity.Property(e => e.Vin)
                .HasMaxLength(254)
                .HasColumnName("vin");
            entity.Property(e => e.Year).HasColumnName("year");

            entity.HasOne(d => d.Client).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.Clientid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_vehicle_associati_client");
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.HasKey(e => e.Warehouseid).HasName("pk_warehouse");

            entity.ToTable("warehouse");

            entity.HasIndex(e => e.Warehouseid, "warehouse_pk").IsUnique();

            entity.Property(e => e.Warehouseid)
                .ValueGeneratedNever()
                .HasColumnName("warehouseid");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.Capacityunit)
                .HasMaxLength(254)
                .HasColumnName("capacityunit");
            entity.Property(e => e.Location)
                .HasMaxLength(254)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Warehousestock>(entity =>
        {
            entity.HasKey(e => e.Warehousestockid).HasName("pk_warehousestock");

            entity.ToTable("warehousestock");

            entity.HasIndex(e => e.Warehouseid, "association31_fk");

            entity.HasIndex(e => e.Sparepartid, "association32_fk");

            entity.HasIndex(e => e.Warehousestockid, "warehousestock_pk").IsUnique();

            entity.Property(e => e.Warehousestockid)
                .ValueGeneratedNever()
                .HasColumnName("warehousestockid");
            entity.Property(e => e.Currentquantity).HasColumnName("currentquantity");
            entity.Property(e => e.Minimumquantity).HasColumnName("minimumquantity");
            entity.Property(e => e.Sparepartid).HasColumnName("sparepartid");
            entity.Property(e => e.Warehouseid).HasColumnName("warehouseid");

            entity.HasOne(d => d.Sparepart).WithMany(p => p.Warehousestocks)
                .HasForeignKey(d => d.Sparepartid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_warehous_associati_sparepar");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Warehousestocks)
                .HasForeignKey(d => d.Warehouseid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_warehous_associati_warehous");
        });

        modelBuilder.Entity<Workorder>(entity =>
        {
            entity.HasKey(e => e.Workorderid).HasName("pk_workorder");

            entity.ToTable("workorder");

            entity.HasIndex(e => e.Vehicleid, "association17_fk");

            entity.HasIndex(e => e.Workshopid, "association18_fk");

            entity.HasIndex(e => e.Invoiceid, "association19_fk");

            entity.HasIndex(e => e.Workorderid, "workorder_pk").IsUnique();

            entity.Property(e => e.Workorderid)
                .ValueGeneratedNever()
                .HasColumnName("workorderid");
            entity.Property(e => e.Actualend).HasColumnName("actualend");
            entity.Property(e => e.Actualstart).HasColumnName("actualstart");
            entity.Property(e => e.Externalservicecost).HasColumnName("externalservicecost");
            entity.Property(e => e.Invoiceid).HasColumnName("invoiceid");
            entity.Property(e => e.Laborcost).HasColumnName("laborcost");
            entity.Property(e => e.Mileage).HasColumnName("mileage");
            entity.Property(e => e.Partscost).HasColumnName("partscost");
            entity.Property(e => e.Scheduledstart).HasColumnName("scheduledstart");
            entity.Property(e => e.Status)
                .HasMaxLength(254)
                .HasColumnName("status");
            entity.Property(e => e.Totalcost).HasColumnName("totalcost");
            entity.Property(e => e.Vehicleid).HasColumnName("vehicleid");
            entity.Property(e => e.Workordernumber).HasColumnName("workordernumber");
            entity.Property(e => e.Workshopid).HasColumnName("workshopid");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Workorders)
                .HasForeignKey(d => d.Invoiceid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_workorde_associati_invoice");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Workorders)
                .HasForeignKey(d => d.Vehicleid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_workorde_associati_vehicle");

            entity.HasOne(d => d.Workshop).WithMany(p => p.Workorders)
                .HasForeignKey(d => d.Workshopid)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_workorde_associati_workshop");
        });

        modelBuilder.Entity<Workshop>(entity =>
        {
            entity.HasKey(e => e.Workshopid).HasName("pk_workshop");

            entity.ToTable("workshop");

            entity.HasIndex(e => e.Workshopid, "workshop_pk").IsUnique();

            entity.Property(e => e.Workshopid)
                .ValueGeneratedNever()
                .HasColumnName("workshopid");
            entity.Property(e => e.Code)
                .HasMaxLength(254)
                .HasColumnName("code");
            entity.Property(e => e.Email)
                .HasMaxLength(254)
                .HasColumnName("email");
            entity.Property(e => e.Location)
                .HasMaxLength(254)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .HasMaxLength(254)
                .HasColumnName("name");
            entity.Property(e => e.Openinghours)
                .HasMaxLength(254)
                .HasColumnName("openinghours");
            entity.Property(e => e.Phone)
                .HasMaxLength(254)
                .HasColumnName("phone");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}